languare: node_js
branches:
  only:
  - master
node_js:
- 12
service:
- docker
script:
- export TAG=$(cat package.json | python -c "import sys,json; print(json.load(sys.stdin).get('version'))")
- docker build -t bassaer/ts-stress-server -t bassaer/ts-stress-server:$TAG .
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/docker_push.sh
  on:
    branch: master
