apiVersion: v1
kind: Service
metadata:
  labels:
    app: ts-stress-server
  name: ts-stress-server
spec:
  type: ClusterIP
  selector:
    app: ts-stress-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
